export const STORE_ATRIBUT = 'STORE_ATRIBUT';
export const GET_ATRIBUTI = 'GET_ATRIBUTI';
export const SET_ATRIBUTI = 'SET_ATRIBUTI';

export const STORE_TIP_ATRIBUTA = 'STORE_TIP_ATRIBUTA';
export const GET_TIPOVI_ATRIBUTA = 'GET_TIPOVI_ATRIBUTA';
export const SET_TIPOVI_ATRIBUTA = 'SET_TIPOVI_ATRIBUTA';
export const SET_TIP_ATRIBUTA = 'SET_TIP_ATRIBUTA';
