export const STORE_FIZICKO_LICE = 'STORE_FIZICKO_LICE';

export const GET_FIZICKA_LICA = 'GET_FIZICKA_LICA';
export const SET_FIZICKA_LICA = 'SET_FIZICKA_LICA';

export const GET_FIZICKO_LICE = 'GET_FIZICKO_LICE'
export const SET_FIZICKO_LICE = 'SET_FIZICKO_LICE';

export const UPDATE_FIZICKO_LICE = 'UPDATE_FIZICKO_LICE';
export const DELETE_FIZICKO_LICE = 'DELETE_FIZICKO_LICE';