export const STORE_KATEGORIJA_ROBE = 'STORE_KATEGORIJA_ROBE';
export const GET_KATEGORIJE_ROBE = 'GET_KATEGORIJE_ROBE';
export const SET_KATEGORIJE_ROBE = 'SET_KATEGORIJE_ROBE';

export const STORE_PODKATEGORIJA_ROBE = 'STORE_PODKATEGORIJA_ROBE';
export const GET_PODKATEGORIJE_ROBE = 'GET_PODKATEGORIJE_ROBE';
export const SET_PODKATEGORIJE_ROBE = 'SET_PODKATEGORIJE_ROBE';